name: Build and publish DGL cugraph CI docker images workflow
on: 
  workflow_dispatch:
  # schedule:
  #   - cron: '30 1,12 * * *'

jobs:
  docker:
    runs-on: linux-amd64-cpu16
    env:
      DOCKERHUB_USERNAME: '${{ secrets.GPUCIBOT_DOCKERHUB_USER }}'
      DOCKERHUB_TOKEN: '${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}'
    strategy:
      matrix:
        CUDA_VER:
          - "11.5"
        CUDATOOLKIT_VER:
          - "11.6"
        PY_VER:
          - '3.9'
        LINUX_VER:
          - "ubuntu18.04"
        PYTORCH_VER:
          - "1.12.0"
        RAPIDS_VER:
          - '22.12'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders
      - if: '${{ env.DOCKERHUB_USERNAME != '''' && env.DOCKERHUB_TOKEN != '''' }}'
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: '${{ env.DOCKERHUB_USERNAME }}'
          password: '${{ env.DOCKERHUB_TOKEN }}'
      - name: Build and push
        timeout-minutes: 30
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "./cugraph_nightly_torch.Dockerfile"
          platforms: ${{ matrix.CUDA_VER >= '11.2.2' && matrix.LINUX_VER != 'centos7' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          push: true
          pull: true
          build-args: |
            CUDA_VER=${{ matrix.CUDA_VER }}
            CUDATOOLKIT_VER=${{ matrix.CUDATOOLKIT_VER }}
            LINUX_VER=${{ matrix.LINUX_VER }}
            PYTHON_VER=${{ matrix.PY_VER }}
            PYTORCH_VER=${{ matrix.PYTORCH_VER }}
            RAPIDS_VER=${{ matrix.RAPIDS_VER }}
          tags: rapidsai/cugraph_nightly_torch-cuda:${{ matrix.CUDA_VER }}-base-${{ matrix.LINUX_VER }}-py${{ matrix.PY_VER }}-pytorch${{ matrix.PYTORCH_VER }}-rapids${{ matrix.RAPIDS_VER }}
